/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import Clases.Pais;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author aacev
 */
public class VistaMenu extends javax.swing.JFrame {
    
    private List<Pais> listaMaestraDePaises;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMenu.class.getName());

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
        setLocationRelativeTo(null);
        cargarDatosDePrueba();
    }
    // 4. AÑADE ESTE MÉTODO COMPLETO PARA CREAR Y LLENAR LA LISTA
    private void cargarDatosDePrueba() {
        
        this.listaMaestraDePaises = new ArrayList<>();
        
        this.listaMaestraDePaises.add(new Pais("Chile", "South America", "South America", 756102.0f, 1810, 19116201, 80.5f, 258.5f, "Republic", "Gabriel Boric", "Santiago", "CHL"));
        this.listaMaestraDePaises.add(new Pais("Argentina", "South America", "South America", 2780400.0f, 1816, 45376763, 76.7f, 383.1f, "Republic", "Javier Milei", "Buenos Aires", "ARG"));
        this.listaMaestraDePaises.add(new Pais("Japón", "Asia", "Eastern Asia", 377975.0f, -660, 125507472, 84.5f, 5065.0f, "Constitutional Monarchy", "Fumio Kishida", "Tokyo", "JPN"));
        
        System.out.println("Lista de paises creada. Total: " + this.listaMaestraDePaises.size() + " paises.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        bttnControlDeUsuario = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblConsultaDeDatos = new javax.swing.JLabel();
        bttnPais = new javax.swing.JButton();
        bttnCiudad = new javax.swing.JButton();
        bttnIdioma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registro poblacional internacional");

        bttnControlDeUsuario.setText("Control de usuarios");
        bttnControlDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnControlDeUsuarioActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(bttnControlDeUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(bttnControlDeUsuario)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bttnControlDeUsuario)
        );

        lblConsultaDeDatos.setText("Consulta de datos:");

        bttnPais.setText("Pais");
        bttnPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPaisActionPerformed(evt);
            }
        });

        bttnCiudad.setText("Ciudad");
        bttnCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCiudadActionPerformed(evt);
            }
        });

        bttnIdioma.setText("Idioma");

        jLayeredPane1.setLayer(lblConsultaDeDatos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bttnPais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bttnCiudad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(bttnIdioma, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConsultaDeDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnIdioma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(lblConsultaDeDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnPais)
                .addGap(12, 12, 12)
                .addComponent(bttnCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttnIdioma)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnControlDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnControlDeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnControlDeUsuarioActionPerformed

    private void bttnPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPaisActionPerformed

        VistaPais vistaPais = new VistaPais(this.listaMaestraDePaises);
        vistaPais.setVisible(true);
    }//GEN-LAST:event_bttnPaisActionPerformed

    private void bttnCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCiudadActionPerformed
            
            VistaCiudad vistaCiudad = new VistaCiudad(this.listaMaestraDePaises);
            vistaCiudad.setVisible(true);
    }//GEN-LAST:event_bttnCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCiudad;
    private javax.swing.JButton bttnControlDeUsuario;
    private javax.swing.JButton bttnIdioma;
    private javax.swing.JButton bttnPais;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLabel lblConsultaDeDatos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    
}
